---
title: "Primer on Neurointerventional Devices"
author: "J Lynch"
format:
  html:
    toc: true
    toc-depth: 2
    toc-location: left
    number-sections: true
    citations:
      bibliography: [book.bib, packages.bib, My Library.bib]
      biblio-style: apalike
      link-citations: true
bibliography: [book.bib, packages.bib]
biblio-style: apalike
project:
  type: book
---

# Introduction

The number of neurointerventional devices has increased dramatically in recent years due to advances in engineering and a widened scope of neurointerventional practice. Knowledge of the characteristics of specific devices is integral to the practice of neurointervention and this chapter serves as a useful introduction. Choice of one device over another in a particular situation may mean the difference between procedural success or failure. Information on compatibility and sizing these devices, including compatibility, is available on the free non-commercial online resource [www.neurotool.org](http://www.neurotool.org/). 

**A note on units**

By convention different units are used in neurointervention for different purposes mainly for historical reasons:

- **Inches (in)** are used for the inner luminal diameter of catheters and the diameter of wires.
- **French Gauge (Fr)** (or just **French**) is generally used for the outer diameter of catheters and the inner diameter of sheaths. 1 French is 1/3 of a millimetre.
- **Centimetres** and **millimetres (cm, mm)** are generally used for length.
- **Birmingham gauge (G)** (or just **gauge**) is used for the outer diameter for hypodermic needles. Counterintuitively the larger the gauge the smaller the diameter.


# Guidewires

  Guidewires are engineered to be flexible, pushable (capable of transmitting force to the tip), gentle on vessels, and torque-able (controlled rotation of the tip). To accomplish this, they feature soft, atraumatic tips and more rigid shafts. Guidewires can possess straight or angled tips, which are often shapeable. ‘J’-angled tips, in particular, are less prone to dissection and perforation of vessels. Wires can be torqued by hand or by using torque devices screwed onto the end of the wire. Wires can be standard or exchange length. Exchange wires are double the length of the catheter they are used with so that the catheter can be fully removed keeping the wire in place.

  **Standard diameter wires**

- Wires used in combination with angiographic or guide catheters are most commonly of 0.035” or 0.038” diameter. 
- They must be flushed before withdrawal from packaging.

***Commonly used wires for diagnostic angiography***

- The Glidewire (Terumo) is probably the most commonly used guidewire for selecting the brachiocephalic, subclavian, carotid, and vertebral arteries. It is made of a nitinol alloy core with a tungsten-infused polyurethane jacket, which provides radiopacity, and a hydrophilic coating, which increases lubricity. The wire comes in various sizes but the 0.035” 180 cm wire is considered the most versatile, while the 260 cm version is used for catheter exchange. It typically has an angled tip, although straight shapeable and J-tip versions are also available. There is a stiff version that confers enhanced support. For navigating tortuous aortic arch vessels the Glidewire Advantage is an option. This version is also available in 0.035” diameter with lengths of 180 cm and 260 cm and is designed to provide support and torque-ability.
- The Amplatz wire (multiple manufacturers such as Boston Scientific and Cook Medical) is a stainless steel wire with flat-wire coils and a polytetrafluoroethylene (PTFE) coating to improve lubricity. It is very supportive when navigating a catheter through tortuous vessels. 0.035” and 0.038” diameters are available and there are a range of lengths and stiffness variants. The wire comes with straight (shapeable) or J-tips and stiff and extra stiff variants are available. 

**Microwires**

- Microwires are used inside small, fragile vessels, particularly the intracranial segments of vessels. 
- To aid navigation, these wires are typically equipped with torquing devices and shapers.
- They must be flushed before withdrawal from packaging.
- Microwires have shapeable tips, which can be moulded using the supplied metal shapers. A gentle curve is ideal for selecting vessels, while a J curve is less traumatic but reduces vessel selection ability. For navigating acute angled vessel bifurcations a double curve consisting of a tight distal angled curve and a broader, more proximal angle is helpful. 
- To achieve very tight distal curves (up to 1 mm), the wire can be threaded through the shaping device until a tiny length protrudes out. By gently tapping on the end of the protruding wire, a very tight curve can be formed.
- When a wire has a more tightly curved tip it needs to be back-loaded for insertion into the microcatheter as the curve prohibits direct insertion without damage. This process involves threading the supplied hollow introducer device via the stiff back-end of the wire all the way until it reaches the tip, straightening the wire tip for insertion into the hub. It is crucial to avoid shaving off the hydrophilic coating layer when threading wires with this type of coating as this substance may embolise if inadvertently inserted into the bloodstream.

***Commonly used microwires***

- The Synchro (Stryker) is a general purpose microwire. It is very torqueable. 0.014” and 0.010” diameter variants are available. The wire comes in 200 cm and 300 cm (exchange length) versions. The tip is shapeable and pre-shaped versions are available. There are ‘support’ versions that provide enhanced proximal support and ‘select’ variants that have improved torqueability.
- The Traxcess (Microvention) is a general purpose microwire. It is 0.014” or 0.007” in diameter and ~200 cm in length. The 0.014” can be used with an additional 115 cm docking wire that attaches on to the end of the wire for exchange manoeuvres. The tip is softer than the Synchro wire but the wire is less torqueable. The Traxcess shaft is actually 0.012” allowing it to be inserted into microcatheters, usefully the 0.013” Marathon, despite the apparent size discrepancy. 
- The Transend (Stryker Neurovascular) is a general purpose microwire that comes in 0.010” and 0.014” diameters. The 0.014” version comes in 182 cm, 205, and 300 cm lengths and the 0.010” version is 200 cm.
- The Hybrid (Balt) is a microwire that can be used for navigation into the very distal cerebral circulation in pathologies involving smaller vessels, for AVM/DAVF embolisation. It is soft and available in diameters as small as 0.007”. Other diameters include 0.008”, 0.010”, 0.012”, and 0.014”. It has a shapeable tip and comes in straight, angled, and double-angled varieties.
- The Mirage (Medtronic) is a 0.008” microwire used for similar purposes to the Hybrid. It is subjectively slightly stiffer which might be useful when pushability is required. It is mainly used for small vessels in AVM/DAVF embolisation. 
- The Asahi Chikai (Asahi) is available in 0.008”, 0.010”, 0.014”, and 0.018” diameters. The smaller versions are mainly used in AVM/DAVF embolisation. The “black” variant has greater radiopacity.
- Terumo also sells hydrophilic wires in sizes down to 0.014”. 

# Sheaths and Catheters

Catheters require certain characteristics: they should provide proximal support, maintaining a stable position without prolapsing or kinking, be gentle on vessels, easily navigate through tortuous vasculature, have a small outer diameter to access narrow vessels, and a large inner diameter for accommodating devices. Additionally, they should be non-thrombogenic and affordable. In practice, a balance between these desirable design features is necessary.

Sheaths and catheters must be flushed inside and outside before use.

A *coaxial* configuration refers to a microcatheter being inserted into a guide catheter or a long sheath. A *triaxial* configuration refers to inserting a microcatheter into an intermediate (or ‘distal access’) catheter, which is then inserted into a guide catheter or a long sheath. 

**Vascular sheaths**

- Vascular sheaths are placed at the vascular access site to reduce friction between the catheter and the vessel wall. 
- The size of the sheath is indicated by the largest device that can be inserted through it. For example, a 6 Fr guide catheter can be inserted into a 6 Fr sheath. 
- The outer diameter of the sheath is usually about 2 Fr sizes larger than the inner diameter. However, newer sheaths are now available with an outer diameter of just 1 Fr larger than the inner, particularly advantageous for radial and paediatric access. These include the Prelude Ideal (Merit) and Glidesheath Slender (Terumo). These typically come with micropuncture needles and microwires for introduction into smaller, more delicate, vessels.
- Sheaths used in neurointervention typically range in size from 4–9 Fr. For interventional procedures 5–8 Fr sheaths are generally used since most guide catheters are sized between 5–8 Fr. 
- The larger the sheath the greater the rate of puncture site complications. 

**Angiographic and select catheters**

- Catheters used for cerebral angiography come in a range of sizes and shapes but usually range from 4 to 6 Fr. They typically have tip curves to aid in selective catheterisation. Different vessel angulations may favour specific curves. Occasionally it is necessary to try different catheters to achieve success. 
- ‘Select’ catheters are introduced inside the lumen of guide catheters/long sheaths and used to select the great arteries of the aortic arch. It is necessary that they are longer than the guide catheter/long sheath in which they are inserted.

**Guide catheters and long sheaths**

- A *guide catheter* is flexible and relatively wide internal diameter catheter that is typically inserted through a short sheath in a peripheral artery, such as the common femoral or radial artery. The catheter's tip is typically placed in the carotid or vertebral arteries to provide a stable platform for more distal intervention. 
- 6 Fr guide catheters can generally accommodate two devices simultaneously, for example a microcatheter and balloon microcatheter, or an intermediate catheter large enough for a single microcatheter. 8 Fr catheters can accommodate a 6 Fr intermediate catheter. 
- Depending on the stiffness of the catheter and the tortuosity of the vasculature, the tip is placed in different locations. In the ICA, guide catheters with soft tips like the Benchmark may be placed in the cavernous segment if the artery is relatively straight but generally not distal to the ophthalmic origin. In the vertebral artery soft catheters can sometimes be brought into the V4 segment if the anatomy is favourable. Stiffer catheters should be kept more proximal to avoid vessel dissection. 
- A *long sheath* serves the same purpose as a guide catheter, and in practice is often exactly the same device, the difference being it is sited directly in the vessel without an additional vascular sheath. The main advantage of a long sheath therefore is that it requires a smaller arteriotomy at the puncture site. For example, an 8 Fr guide catheter requires an 8 Fr vascular sheath which, in turn, requires a 10 Fr arteriotomy (the outer diameter of a short sheath is typically 2 Fr larger than the inner diameter). However, an identically proportioned 8 Fr long sheath creates just an 8 Fr arteriotomy as the additional vascular sheath is not used. 
- In practice many guide catheters can be used as long sheaths and vice versa. This can lead to confusion over size designations. Guide catheters are usually named after their inner diameter whereas long sheaths are named after their outer diameter (like other sheaths). Therefore an identically proportioned device may be sold in two versions with a different labelled size. For example, the 8 Fr Fubuki (Asahi) guide catheter is also sold as the 6 Fr Fubuki long sheath. The only difference is that the latter is packaged with an obturator. The obturator is placed inside the long sheath and reduces the ledge between the wire and the catheter as it is introduced through the arteriotomy into the artery over a wire. 
- The conventional vascular sheath is often placed first and then exchanged for the long-sheath with the same outer diameter. 

***Commonly used devices***

- The Neuron Max (Penumbra) is a general purpose long sheath/catheter. It is useful when proximal support and a relatively large inner diameter (0.088”) is required. The tip is usually positioned in the straight cervical segment of the internal carotid or the extracranial vertebral artery. The tip is not generally brought inside the skull to avoid vessel dissection. It is also not commonly used via the radial artery as the catheter may kink. The catheter comes in 80 or 90 cm lengths. It can be used with or without an 8 Fr femoral sheath. Like all long sheaths it comes with an obturator.
- The AXS Infinity LS (Stryker) is a general purpose long sheath/catheter similar to the Neuron Max with an identical inner diameter (0.088”). It is supportive proximally (probably more so) and can be used via the radial artery without a sheath providing the vessel is large enough. It provides a stable platform when used in tortuous vessels. The AXS Infinity LS Plus is a larger, more flexible, version with a 0.091” inner diameter but still retaining the 8 Fr outer diameter.
- The Benchmark (Penumbra) is a general purpose catheter that is smaller and more flexible than the above-mentioned. It can be used via the femoral artery with a 6 Fr groin sheath and via the radial artery with or without a sheath. The inner diameter is 0.071” and it comes in 95, 105, and 115 cm lengths. It has a very flexible distal segment that may be taken intracranially, obviating the need for intermediate catheters. It does not provide as much proximal support as larger catheters. There are newer Benchmark BMX 81 and 96 versions with, respectively, 7 Fr outer diameter/0.081” inner lumens and 8 Fr outer diameter/0.96” inner lumens. 
- The Envoy (Cerenovus) is a relatively stiff, inexpensive, guide catheter that comes in 5, 6, and 7 Fr variants. Lengths vary from 90 to 105 cm. 
- The RIST (Medtronic) is a guide catheter designed for radial use. The intention is to provide good proximal support but allow the tip to be placed distally, obviating the need for an intermediate catheter. 
- A range of other modern guide catheters/long sheaths are available. These tend to be proximally supportive and distally atraumatic. The 0.090” Cerebase DA (Cerenovus) is available in 70–95 cm lengths and has a very soft tip that can be brought distally. It can be used radially. The 0.088” Ballast (Balt) is a 80–100 cm guide catheter/long sheath which is often used radially. 

**Intermediate, distal access, and reperfusion catheters**

- *Intermediate* or *distal access* catheters are inserted within guide catheters/long sheaths and used to provide a more stable and distal position through even tortuous anatomy. They are of particular use when lots of proximal support is required, for example deploying a flow-diverter.
- *Reperfusion* or *aspiration* catheters are inserted within guide/catheters and designed to be taken to the clot-face during thrombectomy. Negative aspiration force is applied to retrieve the clot. These catheters tend to have large inner lumens so they can apply the greatest negative pressure to the thrombus.
- There is overlap between the design of intermediate and reperfusion catheters and many can perform both functions.

***Commonly used devices***

- The Navien (Medtronic) is an intermediate catheter that comes in 0.058” and 0.072” inner diameter variants. It is a very supportive catheter and a good choice for stent and flow-diverter deployment. The support comes at the cost of rigidity meaning that it cannot be taken as far distally as some other devices. It is not used as a reperfusion device.
- The Sofia (Microvention) is a very flexible and trackable catheter that can be used as a reperfusion or intermediate catheter. It comes in 5 Fr (0.055” inner diameter), Ex (standing for “eXtra support and eXtra stability” with an 0.058” inner diameter), 6 Fr (0.070” inner diameter), and Plus 6 Fr (0.070” inner diameter) versions. These are highly navigable but not as supportive as some other devices.
- The RED (Penumbra) family of reperfusion catheters include 0.043”, 0.062”, 0.068, and 0.072” inner diameter variants. They have a lubricious outer coating designed to be easily trackable. They can be steam shaped with a supplied mandrel, to help avoid it catching on the ophthalmic origin. 
- The REACT (Medtronic) family of reperfusion catheters comes in 0.068” and 0.071” inner diameters and is designed to be easily trackable. 
- The Vectra (Stryker) family of reperfusion catheters include 0.043”, 0.071” and 0.074”, and 0.078” inner diameters. The latter is one of the largest reperfusion catheters available. 
- The 3MAX, 4MAX, and 5MAX (Penumbra), are smaller reperfusion catheters with lumen sizes of, respectively, 0.035”, 0.041”, and 0.054”. The 3MAX is especially good for aspiration of clots in small vessels. 
- There are multiple other reperfusion catheters such as the Embovac/Large Bore Catheter (Cerenovus) and Zoom 71 (Imperative Care). The MIVI Q (MIVI Neuroscience) features a novel design consisting of a flexible catheter section mounted on a control wire, which is designed to result in a greater overall system radius. 
- The Fargo Mini (Balt) is a small and highly flexible intermediate catheter with an inner diameter of 0.040” and available in lengths 120 and 135 cm. It is useful in providing support for a single microcatheter. For example the Fargo Mini can be positioned in the internal maxillary artery when taking a distal microcatheter into the middle meningeal artery to perform a fistula embolisation.

**Microcatheters**

- Microcatheters are used to access the small, distal vasculature or vascular lesions lying more proximally. They can be used to deliver coils, stents, liquid embolics, particles and other devices/substances. They generally have very soft tips.
- Microcatheter tips can be heat shaped using a supplied mandrel to enhance catheterisation of vessels or aneurysms. Some systems also come with various pre-shaped tip options. Heat shaping also softens the tip, potentially reducing vessel trauma. 
- There is a radio-opaque tip marker. Microcatheters used for coil embolisation additionally have a proximal coil detachment marker. 

***Commonly used microcatheters***

- The SL-10 (Stryker) is a general purpose microcatheter commonly used for coil embolisation. The inner diameter is 0.0165” and the length is 150 cm and there is a distal coil detachment marker. It can also be used to deliver low-profile stents such as the Atlas (Stryker), LEO+ baby (Balt), and LVIS Junior/Evo (Microvention). The SL-10 is not DMSO compatible but can deliver NBCA glue. Officially, only the SL-10 is compatible with Stryker Target coils. 
- The Echelon-10 and Echelon-14 (Medtronic) general purpose microcatheters are commonly used for coil embolisation, low profile stent placement, and liquid embolic use. They both have the same inner diameter of 0.017” but the outer diameter of the 14 is greater than the 10 providing more support. The outer diameter of the Echelon-10 is less than the SL-10. Both microcatheters are 150 cm in length and feature distal coil detachment markers. The Echelon-14 is better suited for situations where rigidity is necessary, providing support during coiling of an acutely angled aneurysm after steam-shaping the catheter. In contrast, the Echelon-10 is more useful when space within the guide catheter is limited. Both microcatheters are compatible with DMSO allowing Onyx (and other liquid embolic) embolisation.
- The Headway (Microvention) microcatheter comes in 0.017”, 0.021”, and 0.027” sizes. The 0.017” variant (called the Headway 17 Advanced) is another 150 cm microcatheter similar to the Echelon and SL-10 that has a distal coil detachment marker. The 0.017”, 0.021” and 0.027” microcatheters are useful for delivering stents and flow-diverters. The Headway catheters are DMSO compatible.
- The Headway Duo (Microvention) low profile microcatheter comes in two sizes which are named after their lengths rather than their diameters. The Headway Duo 156 is 156 cm long and has an inner diameter of 0.0165”. It has a coil detachment marker. It is one of the longest and narrowest of all the coiling microcatheters. The Headway Duo 167 is 167 cm long and has an inner diameter of 0.013”. It is DMSO compatible and useful for liquid embolic delivery for AVF/AVM embolisation. Whilst the 167 length version does not have a coil detachment marker it can be used to deliver small coils if necessary (specifically the Barricade from Balt, and ED 10 from Kaneka). The Target Nano (Stryker) coils also usually fit into the catheter although not reliably (they may get stuck or not detach).
- The Magic (Balt) is low-profile microcatheter with 1.2, 1.5, or 1.8 Fr outer distal tips. These may be used with wires of maximum sizes respectively of 0.008”, 0.009”, and 0.010”. It is typically used for NBCA glue embolisation and is *not* DMSO compatible. The Spif Flow coils (Balt) coils can be delivered through this microcatheter. Preparation and usage is slightly different than other microcatheters: 
    - Flush the packaging of the microcatheter before removing it. 
    - The Magic catheter comes with a supplied insertion mandrel that runs the length of the catheter to help push it through the guide catheter. 
    - Slightly withdraw the insertion mandrel and steam shape the tip between your fingers (this requires practice!). 
    - Once the tip is shaped, fully reinsert the mandrel.
    - Load the Magic catheter into the guide catheter. Thread the catheter for a length but do not poke the tip beyond the end of the guide. Next, remove the mandrel and protrude the Magic catheter into the blood vessel. Wait for blood to drip back from the hub.
    - Flush the Magic catheter with a 3 ml syringe of saline. Attach to an RHV. 
- The Magic catheter can be navigated in three ways: leading with a wire (conventional technique), keeping the wire just before the tip, or by injecting jets of saline from a syringe attached to the hub (flow directed technique). The Magic is the only truly flow directed microcatheter.
- The Sonic (Balt) microcatheter is available in 1.2 or 1.5 Fr outer distal tips with inner diameters of, respectively, 0.0090” or 0.012”. Unlike the Magic it is DMSO compatible. The tip of the catheter is detachable which prevents the whole length of the device getting glued into the intracranial circulation or rupturing the vessel when removing the device. It is important to be careful not to prematurely detach the tip of microcatheters with detachable tips when navigating through tortuous vasculature by keeping microwire close to or distal to the tip. There should not be reflux proximal to the detachment point (indicated by a marker) when injecting *n*-BCA. There is an additional, more proximal, marker that should not be refluxed beyond when injecting other liquid embolics (you can reflux slightly more with non-glue liquid embolics). 
- The Marathon (Medtronic) is a DMSO compatible microcatheter with a 1.5 Fr outer distal tip useful for embolisation. Similar to the Headway Duo 167 certain coils can be delivered through this microcatheter. 
- The Apollo (Medtronic) is a DMSO compatible microcatheter available with a 1.5 Fr outer distal tip similar to the Marathon, but it has a detachable tip (which comes in lengths of 1.5, 3, and 5 cm). 
- In addition, several specialist microcatheters are available, each specifically designed for certain applications. For instance, the Via series of microcatheters (including Via-17, Via-27, and Via-33) from Microvention are engineered for WEB deployment, while the Phenom series (Phenom-17, Phenom-21, and Phenom-27) from Medtronic are designed for deploying the Pipeline flow diverter. The XT series (XT-17 and XT-27) from Stryker are created for deploying the Surpass Evolve flow diverter, and the Trevo Pro and Trak-21 microcatheters from Stryker are designed for the Trevo stent retrievers. Although these microcatheters are designed for specific purposes, many of them can also be used in a general purpose fashion. 

# Balloon devices

**Balloon guide catheters**

- Balloon guide catheters are designed with a balloon near their tip, which, when inflated and combined with lumen aspiration, aim to achieve flow reversal during mechanical thrombectomy. This technique is intended to minimise the risk of distal thrombus embolisation into other territories during clot retrieval.
- The balloon has to be prepared before use to remove air in the system by replacing the dead space with at least 50% contrast:saline mixture (similar to angioplasty catheters, see “Angioplasty balloon catheters”). A test inflation is typically performed prior to use. 

***Devices***

- The Merci (Stryker) is an older balloon guide catheter, available in 8– and 9 Fr sizes. 
- Several newer devices with larger inner diameters are now available, such as the Bobby (Microvention) with a 0.086" inner diameter, the Emboguard (Cerenovus) with a 0.087" inner diameter, and the Walrus (Q’Apel) with a 0.087" inner lumen. These devices are compatible with larger reperfusion catheters and are designed to be more easily navigable and proximally supportive. 

**Remodelling balloon catheters**

- Balloon remodelling is the process of temporarily inflating a balloon catheter across the neck of an aneurysm during coil embolisation e.g. to prevent prolapse of coils into the parent artery.
- Similar to balloon guide catheters, balloons used in these devices are soft and compliant and will mould to the shape of the vessel. Balloon inflation is accomplished using a small syringe containing a contrast:saline mixture. The higher the contrast percentage, the greater the visibility but the less the compliance. 

***Single lumen balloon catheters***

- The first devices had a single lumen, i.e., the same lumen where the wire is passed for navigation is also used to inflate the balloon. The seal on the balloon is created when the wire is in place and hence it is important not to withdraw the wire proximal to the tip of the catheter during procedures as the balloon may become filled with blood. 
- Preparation:
    - Flush the plastic case containing the balloon catheter (the dispenser coil) with saline to activate the hydrophilic coating.
    - Prepare a contrast:saline mixture in a pot with about 50–70% contrast.
    - Attach a one-way stopcock to a rotating haemostatic valve (RHV). Then, attach a 5 ml syringe filled with the contrast:saline mixture to the RHV inflation port and flush it with the mixture to remove any air. Tighten the RHV and attach it to the microcatheter. Flush the balloon catheter forward to fully purge the system.
    - Insert the microwire into the balloon catheter lumen via the RHV, but keep it proximal to the distal seal so that it does not protrude from the end. Flush the system again. Advance the guidewire until it passes distal to the catheter tip. The wire acts as a seal on the balloon at this point. Form a curve on the wire tip if desired. 
    - Use the same 5 ml syringe to perform a test inflation of the balloon to its nominal pressure underwater. Inspect the balloon for any abnormalities or air bubbles. If satisfied, deflate the balloon by aspirating on the syringe with the catheter tip submerged underwater. Flush the system again with contrast-saline and then reinsert the wire beyond the tip.
    - Once satisfied, fill a 1 ml syringe with the contrast-saline mix to about two-thirds full and attach a one-way tap or flow switch to it. Attach this to the inflation port while taking care not to introduce any air bubbles.

***Commonly used single lumen balloon catheters***

- The Hyperform (Medtronic) is a single lumen balloon with 3, 4, and 7 mm diameter sizes. The Hyperform pouts well into the neck of aneurysms. It is used with the supplied X-Pedion 0.010” microwire. Other 0.010” wires risk spontaneous balloon deflation during use, but the Asahi Chikai 10X seems to work well with the device. 
- The Hyperglide (Medtronic) is a similar single-lumen balloon available in 3, 4, and 5 mm diameters and longer balloon lengths. Hyperform & Hyperglide are DMSO compatible. 
- The Transform (Stryker) is a single-lumen balloon available in C (“Compliant”) and SC (“Super Compliant”) versions. The C balloon ranges in diameter from 3 to 5 mm and the SC balloon ranges from 3 to 7 mm. One advantage of the Transform is that it can accommodate a 0.014" wire, such as the Synchro-14.
- The Eclipse (Balt) comes in single- and dual lumen versions (see below), in 4–6 mm balloon diameters and 7, 9,1 2, 15 and 20 mm lengths (same as the dual lumen version). It requires an 0.014” wire.
- The Copernic (Balt) is another single lumen balloon that comes in 3–5 mm diameters and 10, 15, 20, 30 lengths and requires the Traxcess 0.014” 0.014”, Hybrid 0.012”, or Hybrid 0.014” wires. The Copernic RC, a larger, longer version with balloon diameters measuring up to 10 mm and lengths up to 80 mm is designed for venous sinus protection during embolisation of dural fistulas. It requires the Transend or Traxcess 0.014” wire for usage. 

***Dual lumen balloons***

- Dual lumen balloons feature one lumen for wire insertion and a separate lumen for balloon inflation. This design allows for continuous irrigation of saline during use, permits the withdrawal of wires proximal to the tip and even (compatible) coil/stent deployment.
- Preparation:
    - Prepare a contrast-saline mixture in a pot with about 50–70% contrast.
    - Attach the microwire introducer or a blunt needle to a 5 ml syringe filled with the contrast:saline mixture and insert it into the bottom of the inflation port. Fill the port from deep to superficial to purge any air. 
    - Remove the needle and attach the syringe directly to the inflation port. Hold the balloon tip vertically and slowly inject the syringe over about 60 seconds. Initially, you may see the balloon inflate with air, but eventually a fluid level will appear, the air will be expelled, and the balloon will fill with fluid. Sometimes, it fills immediately with fluid. Ensure that the balloon is fully inflated by holding it vertically to expel any remaining air.
    - Hold the balloon tip in the contrast-saline mix and aspirate to empty the balloon, being careful not to introduce any air into it.
    - After deflating the balloon, remove the balloon tip from the liquid. Fill a 1 ml syringe with the contrast-saline mix to about two-thirds full and attach a one-way tap or flow switch to it. Attach this to the inflation port while taking care not to introduce any air bubbles.
    - Flush a RHV with saline and attach it to the catheter hub. Insert the microwire into the balloon catheter until the tip protrudes from the end. 

***Commonly used dual lumen balloon catheters***

- The Scepter (Microvention) comes in C (“Compliant”) and XC (“eXtra Compliant”) versions. They all have 4 mm balloon diameters but have different lengths ranging from 10 to 20 mm. The Scepter takes a 0.014” diameter wire. The Scepter is DMSO compatible and can be used to deliver coils and low-profile stents such as the Atlas, LVIS Junior, and LEO baby. 
- The Scepter Mini (Microvention) is a smaller balloon catheter designed for distal access and liquid embolic embolisation. Inflating the balloon prevents reflux of the liquid embolic. It has a 0.009” inner lumen to be used with a 0.008” wire. It should be used with a low viscosity liquid embolic, typically Squid 12. There are some differences in comparison to the normal Scepter:
    - A mandrel is inside the main lumen of the device and needs to be replaced with a wire before use.
    - A 1 ml syringe (instead of 5 ml syringe), 100% contrast, is used for the test inflation. 
    - This is replaced with a 0.25 ml syringe filled with 0.1 ml 100% contrast for use in the body. 
    - The balloon dilates from 1.7 to 2.7 mm in diameter depending on injection of 0.01 to 0.04 ml of fluid. 
    - Usually 0.02 ml is injected, giving a diameter of 2.2 mm.
    - A stopcock rather than a flow-switch should be used to keep the balloon inflated. 
    - The device is compatible with 0.008” or smaller wires. 
- The Eclipse 2L (Balt) has a 6 mm balloon diameter, ranging from 7 mm to 20 mm in length. The Eclipse can be used with a 0.014” wire. The Eclipse is DMSO compatible and can also be used to deliver low-profile stents.

**Angioplasty balloon catheters**

- Angioplasty balloon catheters are non-compliant, of variable size, and used to mechanically expand vascular stenosis. Larger balloons are used for carotid stenosis and smaller balloons have been developed for intracranial stenosis. 
- Balloons are used over a wire (usually a microwire). Angioplasty balloon catheters typically use a ‘rapid exchange’ system whereby the catheter can be exchanged with a carotid stent using conventional length wires.
- Inflation devices are utilised to inflate balloons during procedures, and are specifically designed to measure pressure during inflation, preventing vessel damage and rupture from over-inflation. Pressure can be accurately adjusted using a rotating handle, and the balloons can be rapidly and completely purged by withdrawing the handle.
- Preparation:
    - Prepare a contrast-saline mixture with a ratio of 50% contrast and 50% saline in a pot.
    - Fill a 5 ml syringe with the contrast:saline mixture and attach a blunt needle to it. Insert the needle into the inflation port and fill the port from deep to superficial to avoid creating any bubbles.
    - Fill a 20 ml syringe with the 50% solution.
    - Remove the air from the system by withdrawing the plunger of the syringe to replace it with the contrast-saline mix in the syringe whilst tapping on the hub. Repeat this process three times.
    - Prepare the inflation device by holding the tubing tip in the contrast solution and rotating the handle anticlockwise to fill up the device with solution.
    - Once sufficient solution is inside the device, attach it to a three-way stopcock and attach to the angioplasty balloon.
    - Insert the stiff back end of the wire through the tip of the balloon catheter until the wire's tip is just protruding. Then, shape the wire to the desired curve.
    - Examples of these devices include the pITA (Phenox) which ranges in size from 1.25 to 4 mm and is licensed for intracranial use and the Trek and MiniTrek (Abbott) which are available from 1.2 to 5 mm and designed as coronary angioplasty balloons. 
    - The Neurospeed (Acandis) is an intracranial balloon angioplasty device that enables stenting directly through the same catheter, thereby eliminating the need for potentially risky exchange manoeuvres, and speeding up the procedure.

**Further reading**

- Brinjikji, Waleed, Robert M Starke, M Hassan Murad, David Fiorella, Vitor M Pereira, Mayank Goyal, and David F Kallmes. 2018. “Impact of Balloon Guide Catheter on Technical and Clinical Outcomes: A Systematic Review and Meta-Analysis.” Journal of NeuroInterventional Surgery 10 (4): 335–39.

# Coils

A coil is a metallic wire with a preformed shape that can be detached within an aneurysm or blood vessel to reduce blood flow and induce thrombosis. This process produces a chronic inflammatory response, which involves the organisation of thrombus and fibrosis and eventual healing and stable occlusion.

The first cerebral aneurysm “wiring” and electrothermic coagulation of an ICA aneurysm was performed in 1938 via a direct puncture technique utilising 30 feet of silver-enamelled wire. The Guglielmi Detachable Coils were the first detachable coils used in humans for aneurysm embolisation in 1990.

**Features of coils**

- Almost all coils used in Neurointervention are detachable, which allows for safe repositioning or complete removal if necessary. Coils are typically made from platinum because it is radiopaque and biologically inert. Platinum is also unaffected by electrolysis, utilised for coil detachment. Alternatively, other coils can also be detached using a mechanical system.
- A wide range of coils are available, including electrolytically detachable coils such as Target (Stryker), Galaxy (Cerenovus), the Cosmos, MicroPlex, Hypersoft, Hyperframe, and Hydrofill series (Microvention), Optima and Barricade (Balt), and Kaneka's ED coils. Mechanically detachable coils include Axium (Medtronic), Avenir (Wallaby Medical), and Smart/PC400/PAC400 (Penumbra). Although many different coils are available, their utility is roughly comparable. Some coils may have a slight advantage in specific circumstances depending on factors particularly aneurysm size and shape and access route. 
- Coils are available in various wire diameters to suit different clinical applications. The Spif Flow coils (Balt) have the lowest profile and can fit through the Magic catheters. These are not detachable and therefore cannot be repositioned once inserted. The next smallest coils are the ED-10 (Kaneka) and Barricade (Balt) coils, which can be deployed through 0.013" microcatheters. The Target Nano and Tetra (Stryker) coils are soft coils deployed through standard 0.0165” and 0.017” microcatheters and are good for small aneurysms (at least 1 mm). The SL-10 is the only microcatheter formally compatible with the Stryker Target Nano coils (other microcatheters may occasionally have detachment problems with these coils). The Tetra coils are specifically designed for small, wide-necked, aneurysms. Target Nano and Tetra often work through 0.013” catheters but can be unreliable. The PC400 (Penumbra) are large 0.020” coils and require the PX Slim 0.025” microcatheter. These coils are particularly useful for occluding venous sinuses or large arteries.
- Within a single range of coils the coil diameter reduces as the size of the coil decreases to increase the softness. Generally coils are labelled either ‘10’ or ‘18’, implying 0.010” or 0.018”, however this only approximates the true diameter.
- Coils within a given range are available in different lengths and sizes. The diameter of the loop of the coil is typically listed first, followed by its stretched-out length. The first loop of the coil is usually smaller than the labelled coil diameter as the microcatheter must be positioned inside the aneurysm during deployment.
- Coils are available in two main types: filling and framing. Helical coils have a spring-like shape and are ideal for filling space. Framing coils, on the other hand, create a stable “basket” in which subsequent coils can be placed without protruding outside. The diameter of the basket is typically similar to the spherical aneurysm dome, excluding any irregularities. For an elongated aneurysm, slightly over-sizing the coil may be necessary to fill the entire aneurysm. Complex, 3D, or 360 coils have non-helical shapes and are better for framing the aneurysm and forming the basket.

**Further reading**

- Guglielmi, Guido. 2009. “History of the Genesis of Detachable Coils: A Review.” Journal of Neurosurgery 111 (1): 1–8.

# Carotid stents

- Carotid stents are used to treat stenosis occurring in the cervical section of the carotid artery, frequently in conjunction with angioplasty. They are typically designed with a high radial force.
- The Carotid Wallstent (Boston Scientific) is the only cobalt alloy carotid stent. It is made from a single wire woven into a tubular stent structure.
- The majority of other carotid stents are composed of nitinol (a nickel-titanium alloy). These are generally laser-cut to create a tubular mesh stent structure. They have sequentially aligned annular rings interconnected by bridges.
- Nitinol stents are available in both open and closed cell configurations. Open cell stents, such as Zilver (Cook Medical), have larger gaps between struts which result in larger free cell areas. In contrast, closed cell stents have smaller gaps between struts. 
- Carotid stents may be used with distal embolic filter protection devices such as the SpiderFX (Medtronic) or Emboshield (Abbott) to catch clots thrown off during angioplasty and deployment. 
- Usage of carotid stents is described in (see “Carotid artery stenting”). 

**Further reading**

- Bosiers, Marc, Koen Deloose, Jürgen Verbist, and Patrick Peeters. 2005. “Carotid Artery Stenting: Which Stent for Which Lesion?” Vascular 13 (4): 205–10.

# Aneurysm bridging stents

- Aneurysm bridging stents act as a scaffold by sitting across the neck of the aneurysm to prevent coil prolapse and promote aneurysmal thrombosis. Over time, an endothelialised arterial layer forms over the struts of the stent. 
- Most stents used in neurointervention are self-expanding, i.e. they expand immediately after being pushed out of the microcatheter (using an attached pusher wire). 
- Many stents are manufactured from nitinol and have radiopaque platinum markers. They come in a range of lengths and diameters. Low-profile versions are available that can fit through 0.0165” microcatheters: Neuroform Atlas (Stryker), LVIS Junior/Evo (Microvention), Atlas (Stryker), and LEO Baby (Balt), and Accero/Acclino/Credo (Acandis). 
- Stents can be categorised by the method of manufacture: 
    - Laser cut stents generally have reduced metal surface coverage (around 7–10%) and so are theoretically less thrombogenic. They usually deploy easily without shortening. Examples include the Neuroform Atlas (Stryker), Acclino/Credo (Acandis), Enterprise (Cerenovus), and the Solitaire (Medtronic). 
    - Braided stents generally have a greater metal surface coverage (around 18–23%) and may also provide some flow-diverting properties (theoretically improving occlusion of the aneurysm). Examples include the LVIS, LVIS Evo (Microvention), LEO (Balt), and Accero (Acandis). These can be deliberately “bunched up” over the neck of the aneurysm to improve neck coverage, and may provide some flow-diversion effect. 
- To prevent introducing air into the circulation, stents must be flushed prior to use. This is achieved by introducing the end of the stent sheath into the RHV chamber and slightly tightening the valve. Once saline is seen to drip out the proximal end of the stent sheath flushing is completed. 
- Resheathable stents have the advantage of allowing repositioning during deployment, which can be useful in achieving optimal stent placement. The Atlas stent is non-resheathable whereas the Acclino/Credo, Solitaire, and the Enterprise are resheathable. Unlike most others, the Solitaire AB is an electrolytically detachable stent. Braided stents are generally resheathable to a certain point of deployment (typically 80–90%). 
- Neurointervention stents are generally unsheathed on a pusher wire that becomes detached when the stent is unsheathed proximal to the proximal end of the stent. After deployment, it is usually possible to re-enter the lumen of the stent using this wire.
- In contrast to flow-diverters it is possible with most stents to cross through the struts with a microcatheter to enter the lumen of an aneurysm for coiling after the stent has been deployed. If the braid is fine, as with the LVIS Evo, this can be challenging. Smaller microcatheters (Headway duo 156 and 167) are useful in this situation or microcatheter placement in the aneurysm prior to stent deployment (“jailing” technique) may be employed. 



# Flow diverters

- Flow diverters are braided fine-mesh stents that are placed across the neck of the aneurysm within the parent vessel to facilitate the redirection of blood flow away from the aneurysmal sac. This induces thrombosis of the aneurysm and the formation of an endothelialised arterial layer within the artery over days to months often without requiring coiling of the aneurysm. 
- Adjunctive coil embolisation (usually loosely packed) may result in faster thrombosis and probably reduces the risk of early haemorrhage sometimes seen in the weeks or months following treatment in large and giant aneurysms. 
- The two variables affecting device permeability are porosity and pore density. Porosity is the percentage ratio of metal-free surface area to the total surface area. Pore density is the number of pores per unit surface area. Lower porosity (i.e. greater area percentage of metal over the aneurysm neck) and increased pore density are associated with greater aneurysm occlusion. Flow-diverters generally work better on side-wall rather than bifurcation aneurysms. 
- Devices construction is broadly similar between manufacturers although the alloy differs. Flow diverters are commonly manufactured from cobalt-chromium (for example the Stryker Surpass Evolve) or nitinol (for example Phenox P64/P48, Microvention FRED, and Balt Silk). 
- Extruded wires are woven into a complex collapsible tubular structure that allows the wires to move against each other to adapt to vessel anatomy and curvature. Due to presence of metallic components which activate the clotting system via the platelet pathway, patients conventionally require pre-treatment with dual antiplatelet therapy.
- Many manufacturers have adapted their devices to lower the thrombotic and thromboembolic risk. This involves a combination of precision engineering and polishing the struts to reduce platelet adhesion. A further modification is surface coating (e.g., the Shield coating with Pipeline, and Heal with Derivo). The addition of these agents is not considered to interfere with the physical properties of the device. 
- The struts of flow-diverters are small and are impossible to cross with a microcatheter to enter the aneurysm to place further coils (as with laser cut and braided stents). If coils are required, it is necessary to either coil the aneurysm first i.e. “jail” the microcatheter in the aneurysm whilst deploying the flow diverter and then remove the jailed microcatheter after coiling. Note that the flow diverter will not fully expand until the jailed microcatheter is removed. 
- A description of devices available is given in “Flow Diversion”.

**Further reading**

- Bageac DV, Gershon BS, De Leacy RA. The Evolution of Devices and Techniques in Endovascular Stroke Therapy. In: Dehkharghani S, editor. Stroke [Internet]. Brisbane (AU): Exon Publications; 2021 Jun 18. Chapter 9.
- Biondi A, Primikiris P, Vitale G, Charbonnier G. Endosaccular flow disruption with the Contour Neurovascular System: angiographic and clinical results in a single-center study of 60 unruptured intracranial aneurysms. J Neurointerv Surg. 2023 Sep;15(9):838-843. 
- Dholakia, Ronak, Chander Sadasivan, David J. Fiorella, Henry H. Woo, and Baruch B. Lieber. 2017. “Hemodynamics of Flow Diverters.” Journal of Biomechanical Engineering 139 (2): 021002.

# Stent retrievers

- Stent retrievers are used to retrieve thrombus from the intracranial circulation. 
- Numerous stent retrievers are now available including the Solitaire (Medtronic), Trevo (Stryker), Embotrap (Cerenovus), CatchView (Balt), pRESET (Phenox), Aperio Hybrid (Acandis), and Tigertriever (Rapid Medical). 
- Stent retrievers are generally laser cut and made of nitinol. 
- Typical labelled unconstrained diameters for stentrievers are between 3 mm and 6 mm. Note that labelled size is usually larger than the vessel diameters they are to be used in (for example 3 mm stent retrievers can often be used in smaller vessels such as 1.5 or even 1 mm). 
- Larger stent retrievers are usually delivered through 0.027” or 0.021” microcatheters. The lowest profile device is currently the Tigertriever 13 which fits through 0.013” microcatheters like the Marathon. The Tigertriever devices also, uniquely, are not self-expanding but their expansion is controlled via a hand-adjustable lever. They can thus be adjusted to the vessel size. The device is therefore similar in design to the Comaneci device. 
- Usefully, the Catchview Mini (Balt) can also be deployed through the 0.013” Headway Duo (despite the apparent labelled size discrepancy). 
- The Nimbus (Cerenovus) is a specifically designed “rescue” stent retriever for tough clots, intended to be used after failure of standard stent retrievers. After deploying the stent and waiting, the microcatheter is re-advanced into the clot to “pinch” it against the stent retriever before retrieval. 


# Intrasaccular and neck bridging devices

- These sit inside (intrasaccular) or across the neck of (neck-bridging) aneurysms. They are designed to treat aneurysms that are difficult to embolise with simple coiling, especially wide-necked bifurcation aneurysms.
- A key advantage of intrasaccular devices is their placement within the aneurysm itself rather than in the parent artery, minimising the need for antiplatelet medication. Consequently, they can be used more safely in acutely ruptured aneurysms.
- In elective aneurysms, patients might still be given a loading dose of antiplatelets before the procedure in case bail-out stenting is required. If stenting is not performed, aspirin alone is often continued for several weeks afterwards to reduce the risk of delayed thromboembolic complications. However, these medications are usually not required in the long term.


# Particles and Sclerosants

**Particles**

- Particles function by lodging within and obstructing small blood vessels. This results in reduced blood flow, which induces an inflammatory response and thrombosis. Typically, particle embolisation is temporary. 
- They are cost-effective and versatile, making them useful in a variety of procedures, including tumour embolisation, epistaxis, and the middle meningeal artery embolisation.
- Particles are composed of either polyvinyl alcohol or spherical acrylic polymer (microspheres). The latter may have a reduced tendency to clump together (resulting in a lower chance of inadvertent catheter blockage). 
- They come in sizes ranging from 50 to 1200 μm. In tumour embolisation the smaller the size the greater the risk of penetrating intra-tumoural anastomoses or dangerous anastomoses and causing ischaemic stroke and/or cranial nerve palsy. 250–300 μm is often a good compromise of efficacy and safety. Particle sizes < 100 μm are generally avoided in neurointervention. 

***How to use particles***

- Particles may be injected with the patient awake as they are non-painful. The risk of non-target embolisation is higher if the patient moves, however. 
- The particles are usually suspended in approximately 50% contrast:saline solution, mixed in a plastic pot prior to aspirating into the syringe. Use different colour or sized syringes for the particles so they can be readily identified.
- It is advisable to use larger microcatheters (e.g. 0.027”) to prevent clumping of particles within the catheter. However this may not always be possible in smaller, more distal, vessels. 
- The microcatheter cannot be wedged. Forward blood flow is required to inject particles. 
- Mixing must be performed continuously during injection as particles have the tendency to sediment and clump together, potentially blocking the catheter. 
- A useful technique to prevent clumping is to connect a 20 ml syringe to a 5 ml syringe using a three-way stopcock, which in turn is connected to the guide catheter. By turning the stopcock to block flow into the guide, you can inject the particle solution back and forth between the 20 ml and 5 ml syringes to mix the particles thoroughly between injections. Once mixed, the solution remains in the 5 ml syringe, ready for injection into the catheter, and the stopcock can be adjusted to allow for catheter injections again.
- Apply a new road map on the biplane. 
- Inject in gentle puffs whilst watching the screen for the increase and decrease in opacity over the target. Watch in particular for reflux into the parent vessel. Initially there will be none but this will develop over the course of the procedure as forward flow is reduced. 
- When significant reflux occurs the injections must be stopped. At this point slowly and continuously inject saline to wash out the particles inside the dead space of the microcatheter whilst screening and continuing to watch for reflux. 
- If the catheter becomes blocked during use it must be removed. 
- After removal of the microcatheter aspirate blood fairly vigorously from the guide catheter before removal.

# Sclerosants

- High concentration alcohol (96%) can be used as an embolisation agent and acts by hyperosmolar damage and as a chemical irritant causing vessel wall ischaemia and anoxia and hence thrombosis. 
- Sclerosants can be injected endovascularly or via direct puncture. It is useful to mix with radiopaque contrast medium for visualisation. 
- Alcohol is painful when injected and so general anaesthesia is generally used. Complications include profound local vasospasm and intoxication. Very rarely cardiac arrest and pulmonary oedema can occur. 
- Sodium tetradecyl sulphate is a detergent that denatures the cell membrane causing thrombosis. The agent is less painful during injection than alcohol. Contrast agents can be added, but it is usually mixed with air to form foam.
- Bleomycin is a cytotoxic antibiotic used in oncology as a chemotherapeutic agent. It is often used for venolymphatic malformations of the head and neck where it is typically injected directly into the lesion (although it can also be delivered intravenously). Very rarely it may cause pulmonary pneumonitis. The agent can cause hyperpigmentation of the skin particularly at sites where sticky plasters and tape are applied (and so these are avoided perioperatively).

**Further reading**

- De Maria L, De Sanctis P, Balakrishnan K, Tollefson M, Brinjikji W. Sclerotherapy for Venous Malformations of Head and Neck: Systematic Review and Meta-Analysis. Neurointervention. 2020 Mar;15(1):4-17. 

# Cyanoacrylate glue

- Cyanoacrylate glue rapidly polymerises into an adhesive permanent solid cast upon contact with ionic substances like blood. This causes an exothermic reaction resulting in temperatures of 80–90°C. Cyanoacrylates contain the same active ingredient as household superglue and are relatively inexpensive in most of the world.
- The agent causes permanent vessel occlusion. Glue is very thrombogenic in comparison to other liquid embolics. 
- A disadvantage with cyanoacrylate use is that the microcatheter may become glued inside the vasculature. The microcatheter therefore has to be removed rapidly after injection. A second disadvantage is that the injection must be performed rapidly, and it can be difficult to control where the agent infiltrates. 
- Cyanoacrylate glue comes in different formulations: 
    - n-Butyl cyanoacrylate (n-BCA) such as Histoacryl (Braun) or Trufill (Cerenovus), 
    - n-BCA mixed with the proprietary monomer metacryloxysulfolane to extend the polymerisation time as with Glubran-2 (GEM), 
    - n-hexyl cyanoacrylate which has a lower adhesive strength to extend injection time without gluing in the microcatheter such as Magic glue (Balt).
- When used, glue is mixed with lipiodol. Lipiodol is an oil-based radiopaque liquid that provides radiopacity, slows polymerisation, and increases viscosity. Usually, concentrations of cyanoacrylate in the mixture vary from 16% to 90%. Determining the correct concentration is an art and varies depending on factors, particularly blood vessel diameter, location of the microcatheter, and velocity of blood flow. To occlude rapid shunts and aneurysms a 50% concentration is typically used. For AVM treatments where the microcatheter is relatively proximal a 25% concentration might be used. 
- The chemical element tantalum, which comes in powder form, can also be added to increase radiopacity. This is typically necessary at 50% or more concentrations of cyanoacrylate. Acetic acid is another substance that can be added to create an acidic solution to delay polymerisation.
- Glue can be injected through practically any microcatheter in contrast to Onyx/Squid/PHIL which require DMSO compatibility. Theoretically some catheters are more resilient than others with the lipiodol component and there is a small risk of dissolving the inner lining of the device. In practice, glue injections are generally quite rapid and so the risk is low. 
- Some syringes (such as the ones sold by Guerbet) are labelled as lipiodol compatible. These are probably more resilient than normal syringes where there is a theoretical risk of the substance damaging the syringes if left inside for a long time. Therefore, if non lipiodol syringes are used it is important to inject soon after drawing up the mixture. 
- Very small catheters such as the ‘flow-directed’ Magic (Balt) and Sonic (Balt) may used to navigate into very small, tortuous, or distal vessels. 
- It is absolutely mandatory to thoroughly flush the microcatheter with a 5–10% glucose (dextrose) solution prior to use to prevent polymerisation of glue within the catheter lumen. 
- The substance is versatile, although its use has been greatly superseded by copolymer liquid embolics such as Onyx. Injecting glue takes experience and may produce unpredictable results. Glue may rapidly penetrate into the vein in high-flow shunts risking venous hypertension and haemorrhage. In comparison to liquid embolics, multiple injections via different pedicles is usually necessary. In comparison however, glue is more thrombogenic and produces less artefact than copolymer liquid embolics.
- Cyanoacrylates and lipiodol can damage balloons and should not be used with balloon catheters.

**How to inject glue **

- Equipment: Two 3 ml syringes (it is suggested that the same size syringe is used every time to inject glue to increase familiarity with the feel of the injection), 2 cc of glue (usually 2 vials), 2 cc of lipiodol (usually 2 vials), and 5% dextrose (or similar non-ionic solution). 
- The glue and lipiodol is mixed in a Gallipot to the desired concentration. Mixing 2 cc of glue and 2 cc of lipiodol would be 50% concentration. Varying ratios of glue:lipiodol affect the rate of polymerisation. Polymerisation times can be increased from about 5 seconds to several minutes by decreasing the amount of glue in the mixture. High-flow shunts require higher polymerisation whereas low-flow shunts or the situation of flow-arrest requires lower concentrations. Tantalum must be added for radiopacity if 50% or more glue is added. Continue to mix the glue until just before injection so that it does not harden.
- The dextrose is drawn up into a labelled 3 ml syringe. 
- The anatomy of the target lesion is defined. A cone beam CT is often helpful. The desired working projection for navigation and injection can then be chosen.
- Often small, distal, arteries must be navigated first. The Magic (Balt) or Sonic (Balt) catheters are particularly useful as they have small diameter tips but supportive proximal shafts. It is often useful to use a triaxial system in these distal vessels, for example using the Fargo Mini (Balt) as an intermediate catheter.
- A wedged position is ideal for injection of glue to prevent reflux. If not wedged make sure that the catheter is not abutting the wall of the vessel or curved back on itself. 
- Perform microcatheter angiography to identify the specific anatomy of the injected vessels. 
- Prepare a blank glue roadmap. Inject contrast into the dead space of the microcatheter.
- Irrigate the hub of the microcatheter with dextrose and then inject through the microcatheter. Screen when injecting the dextrose as contrast within the dead-space of the microcatheter will be expelled from the syringe and you will appreciate what the glue injection will look like.
- Next, inject the glue whilst screening. Watch carefully for reflux whilst injecting. When you have achieved the desired result, aspirate on the syringe whilst rapidly pulling out the microcatheter. Let the guide catheter hub drip back with blood to ensure that no glue particles are within the guide catheter.
- Perform angiography to assess the result.

**Complications**

- Blocked catheter. If the injection is too slow or there has been insufficient dextrose irrigation, the glue can polymerise inside and block the catheter. In addition to this being an annoyance the build-up of pressure can potentially rupture the catheter, causing glue to leak at the rupture site (which may not be seen on the monitor).
- Catheter glued in. There is the risk of gluing the catheter tip in place. Try slowly pulling on the catheter, wait, and then repeat. Pulling on the catheter too hard risks rupturing the vessel. If the catheter cannot be removed without excessive force (risking haemorrhage), it may be necessary to leave it in place cutting the end off at the access site. The patient is typically left on antiplatelet or anticoagulant for a period of time. 
- Toxicity. Cyanoacrylates can cause toxic tissue damage due to the exothermic polymerisation reaction and release of compounds such as acryl acetate and formaldehyde. Perioperative corticosteroids are sometimes used to ameliorate these effects. 

# Copolymer liquid embolics

**Onyx**

- The Onyx Liquid Embolic System (Medtronic) is composed of the copolymer ethylene vinyl alcohol (EVOH) dissolved in dimethyl sulfoxide (DMSO) together with suspended tantalum powder to provide contrast for visualisation under fluoroscopy. The name comes from the dark grey colour of the liquid. Unlike cyanoacrylate, Onyx is non-adhesive. It is particularly useful in DAVF and AVM treatment.
- Onyx requires shaking for 20 minutes prior to use. 
- There are three formulations: 
    - Onyx 18 is 6% EVOH and 94% DMSO. This is lower viscosity and will travel further and penetrate deeper. It is useful for low-flow situations. 
    - Onyx 20 is 6.5% EVOH and 93.5% DMSO. 
    - Onyx 34 is 8% EVOH and 92% DMSO. This is higher viscosity and is useful for embolisation of larger vessels and fistulas.
- In the packet is a 1.5 ml vial of Onyx, a 1.5 ml vial of DMSO, and three 1 ml Onyx delivery syringes. 
- Onyx is delivered by controlled injection through a DMSO-compatible microcatheter. On contact with blood the DMSO solvent dissipates resulting in the EVOH copolymer to precipitate into a spongy cast. Unlike glue, it does not polymerise.

**Squid**

- Squid (Balt) is a non-adhesive liquid embolic with similar properties to Onyx. It has the same composition as Onyx: an EVOH copolymer dissolved in DMSO with tantalum powder (for radiopacity). The main difference is that the tantalum is micronised to decrease the powder grain size. This is intended to cause a slower precipitation of the radiopaque powder, reduce clumping (which can cause microcatheter blockage), to increase visibility and make the agent more homogenous. Squid is also black (like squid ink). 
- Squid requires shaking for 20 minutes prior to use. 
- There are a range of formulas: 
    - SQUID34: High viscosity version. 
    - SQUID34LD: 30% lower radio-opacity (“Low Density”) to avoid the oversaturated effect. Achieved by having a lower amount of tantalum. 
    - SQUID18: The standard formulation for AVM embolisation. 
    - SQUID 18LD: Lower opacity version. 
    - SQUID12: Lower viscosity to allow deeper penetration into the nidus and to reach smaller distal vessels. 
    - SQUID 12LD: Lower opacity version.

**Menox**

- Menox (Meril Life Sciences) is another agent similar to Onyx composed of EVOH copolymer dissolved in DMSO with micronised tantalum powder. 
- It comes in 18, 20, and 34 strengths (also similar to Onyx).

**PHIL**

- Precipitating Hydrophobic Injectable Liquid or PHIL is a non-adhesive liquid embolic with similar properties to Onyx but a different composition. It is composed of two copolymers (polylactide-co-glycolide and polyhydroxyethylmethacrylate) as its active components and triiodophenol (an iodine compound) covalently bound to the two copolymers to give radiopacity. This is then dissolved in DMSO. 
- No shaking is required prior to use. 
- The liquid is white after precipitating (yellow beforehand) so may be more suitable for subcutaneous vascular malformations. It is more homogenous and has fewer artefacts on CT/MRI than Onyx. 
- It is less radio-opaque than Onyx and more difficult to see particularly in small calibre vessels. The liquid has the potential for greater embolic capacity per volume due to a higher concentration of the copolymer. Due to the increased homogeneity there is a lower risk of microcatheter blockage in comparison to Onyx. The substance overall tends to be less viscous than Onyx with improved forward flow. This brings with it, however, the increased possibility of non-target embolisation and early venous penetrance.
- Phil comes with two prefilled 1.0 mL syringes of PHIL and DMSO, respectively.
- The following formulations are available: (1) 25%: Low viscosity (the standard formulation). (2) 30%: Medium viscosity. (3) 45%: High viscosity.

**Obtura** 

- Obtura is a novel third generation liquid embolic agent with promising utility in AVMs. 
- It possesses the unique quality of losing its radiopacity after embolisation, enhancing the visualisation of AVM vasculature and helping to ensure that small, previously radiologically obscure shunts are indeed embolised. There may, therefore, be potential in improving embolised AVM occlusion rates. 

**How to inject copolymer liquid embolics**

- Onyx and Squid (but not Phil) require mechanical shaking 20 minutes prior to injection.
- Navigate the microcatheter to the pedicle to be injected and perform microcatheter angiography. This is usually as close to the point of fistulisation as possible.
- Identify the anatomical space that you want to fill with the liquid embolic, including other feeding pedicles. Ensure that you understand how far you can allow the liquid embolic to reflux and any dangerous anastomoses.
- Prepare a blank glue road map on the fluoroscopy machine.
- Fill the dead space of the microcatheter with DMSO including the hub. DMSO often results in a pungent odour on the breath/skin for several hours after the procedure. Patients should be counselled about this beforehand. This is not related to toxicity. 
- DMSO must be injected slowly because it can cause endothelial necrosis if injected too rapidly. In addition, bradycardia, hypotension, and even asystole can be induced during the injection of DMSO or liquid embolic. This is the trigeminocardiac reflex and is thought to be caused by chemical stimulation of the sensory nerve endings of the trigeminal nerve. Impulses are transmitted back to the motor nucleus of the vagus, via the reticular activating formation. 
- Start screening and injecting the liquid embolic. Initially the liquid embolic will fill the dead space of the microcatheter and nothing will be seen on the monitor. It is useful to start a timer at this point.
- When the liquid embolic exits the microcatheter tip, it will become visible on the screen. Continue injecting if the liquid embolic is moving in the desired direction. However, if it begins to reflux excessively or enters unwanted areas, pause the injection and screening.
- Liquid embolics behave in a ‘lava-like’ fashion with a hard outer crust and liquid centre. The major advantage over glue is the slow precipitation times allowing for longer injections and greater control. This means that liquid embolic can often be injected through a single pedicle of a fistula/AVM as it can reflux into and occlude the other feeding pedicles through the fistula. It has good visibility which comes at the expense of some artefact on CT.
- After a sufficient pause (30–40 seconds), start to inject again. If it again fills an undesirable space then repeat the pause. Eventually the undesirable space will become occluded with the liquid embolic, and it should fill the target space. It might be necessary to build up a plug of the agent proximal to the catheter tip to prevent reflux, and this can take some time. 
- When you think you have achieved sufficient occlusion perform an angiogram from the guide catheter to confirm.
- When removing the microcatheter apply constant, gentle, slow, tension. If the tip is detachable it will probably detach at some point allowing the body of the microcatheter to be retrieved. It is obviously desirable to leave the microcatheter inside the body rather than avulsing a vessel by tugging too hard. 

***Tips***

- The ‘pressure cooker’ technique addresses the issue of proximal reflux of liquid embolic into the injecting pedicle, a common challenge during injections. This involves using a second microcatheter to create a plug of coils and/or glue between the tip of the injecting microcatheter and the detachment zone. This method prevents reflux, establishes a “wedge-flow” condition for the distal injecting microcatheter, reduces blood flow through fistulous compartments, and enhances the capability to push liquid embolic continuously into the nidus. It is beneficial to place the coils first before injecting glue, to avoid unintentionally occluding the feeding pedicle distal to the injecting microcatheter, thereby preserving the route to treat the fistula/AVM. Alternatively, coils alone can be used to form the plug without glue, but this is less effective.
- If the liquid embolic is not shaken for long enough or there is a prolonged delay after removing from the shaker device there may be aggregate formation (clumping) of tantalum. This can result in variable opacification and uneven resistance in the catheter. Microcatheter hub adaptors are provided and may also help with this clumping.
- Trigeminocardiac reflex. Bradycardia, hypotension, and even asystole can be induced during the injection of DMSO or liquid embolic (the ‘trigeminocardiac reflex’). It is usually sufficient to stop injecting and wait to normalise the heart rate and blood pressure. Occasionally vagolytics and sympathomimetics may be required.

**Further reading**

- Chapot, René, Paul Stracke, Aglaé Velasco, Hannes Nordmeyer, Markus Heddier, Michael Stauder, Petra Schooss, and Pascal J. Mosimann. 2014. “The Pressure Cooker Technique for the Treatment of Brain AVMs.” Journal of Neuroradiology = Journal De Neuroradiologie 41 (1): 87–91.
- Vollherbst DF, Chapot R, Bendszus M, Möhlenbruch MA. Glue, Onyx, Squid or PHIL? Liquid Embolic Agents for the Embolization of Cerebral Arteriovenous Malformations and Dural Arteriovenous Fistulas. Clin Neuroradiol. 2022 Mar;32(1):25-38. 
